services:
  - type: web
    name: smart-logistics-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l 3000
    envVars:
      - key: CI
        value: false
